// actions main flashcard
export const BACK_MAIN_FLASHCARD = "BACK_MAIN_FLASHCARD";
export const NEXT_MAIN_FLASHCARD = "NEXT_MAIN_FLASHCARD";
export const RESET_CARD_FOCUS = "RESET_CARD_FOCUS";

// actions tabs
export const CHANGE_CURRENT_TAB = "CHANGE_CURRENT_TAB";

// actions multiple_choice
export const CHANGE_CURRENT_MULTIPLE_CHOICES = "CHANGE_CURRENT_MULTIPLE_CHOICES";
export const CHANGE_MULTIPLE_CHOICES = "CHANGE_MULTIPLE_CHOICES";
export const CHANGE_RESULT_MULTIPLE_CHOICES = "CHANGE_RESULT_MULTIPLE_CHOICES";
export const CHANGE_CARD_FOCUS = "CHANGE_CARD_FOCUS";